/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface ICurveMath {
    function quoteBuy(uint256 vU, uint256 vC, uint256 usdcIn) external pure returns (uint256);

    function quoteSell(uint256 vU, uint256 vC, uint256 coinIn) external pure returns (uint256);

    function usdcToReach(uint256 vU, uint256 vC, uint256 targetVU) external pure returns (uint256);

    function spotPrice(uint256 vU, uint256 vC) external pure returns (uint256);
}
