/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IRoyaltyRouter {
    function initialize(address usdc, address treasury, address owner) external;

    function setFactory(address factory) external;

    function registerSeries(uint256 seriesId, address curve, address characterAccount, uint256 parentSeriesId) external;

    function route(uint256 seriesId, uint256 amount) external;

    function parentOf(uint256 seriesId) external view returns (uint256);

    function accountOf(uint256 seriesId) external view returns (address);

    function curveOf(uint256 seriesId) external view returns (address);

    function earned(address recipient) external view returns (uint256);

    function treasury() external view returns (address);

    function usdc() external view returns (address);

    function factory() external view returns (address);

    function owner() external view returns (address);
}
